version: '3'
services:
  jenkins:
    image: "jenkins/jenkins:lts"
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - 8880:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - ./var/run/docker.sock:/var/run/docker.sock
  agent:
    image: jenkins/ssh-agent:jdk11
    privileged: true
    user: root
    container_name: agent
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABA(...etc)
